### ISSUE TITLE
Potentially invalid allocation in the server example

### ISSUE THREAD

**Issue by Kerollmops** [canonical/raft#128]
In this snippet we can see that the allocation size is defined to be the size of what is under the dereferencing of `fsm` which means that it will be `sizeof(struct raft_fsm)`.

The problem is that it is not the size of the struct we want to use, the correct size should be `sizeof(Fsm)`, I am missing something?

https://github.com/canonical/raft/blob/4d3de31a79b467ee9bc8b27208d87fd53b5c8798/example/server.c#L70-L83

**Comment by freeekanayaka** [comment]
You're right. I've submitted PR #129 to fix this.
