### ISSUE TITLE
state callback

### ISSUE THREAD

**Issue by skypexu** [canonical/raft#147]
Unfortunately, there is not raft state change callback, so user code does not know when the node becomes leader or follower.

**Comment by freeekanayaka** [comment]
I plan to add some kind of support for this in the v1 version of the API, currently being worked on. See https://github.com/canonical/raft/issues/130#issuecomment-615321327 to get some feel of how it will look like.

**Comment by freeekanayaka** [comment]
Please would you also elaborate on why you need such a state change callback in the first place?

There might be valid use cases, but as far as I can tell most applications should not need to react to Raft state changes, and they typically just need to check what the current state is, using `raft_state()`.

**Comment by pyssling** [comment]
@freeekanayaka any news on this callback? In our case the interest is to disable/enable a rpc server based on leadership state, seems like a valid use case, but feel free to suggest alternatives.

**Comment by freeekanayaka** [comment]
Why do you need to disable the server? Can't just the server call `raft_state()` and reply some kind of error if it's not the leader? That'd be a very typical thing to do.

**Comment by stgraber** [comment]
@skypexu @pyssling ping

**Comment by pyssling** [comment]
That works for protocols that contain error responses, but many protocols expect socket state to reflect availability. For these I need a callback to open/close the socket.

**Comment by skypexu** [comment]
yes, raft_state() may work in most cases
