### ISSUE TITLE
Licensing compliance.

### ISSUE THREAD

**Issue by kindofblue** [canonical/raft#150]
A lot of source has almost exact same lines as Willemt's C raft library. 

https://github.com/willemt/raft

But his copyright claim is not in these files.

**Comment by freeekanayaka** [comment]
Please can you point out which ones? This library was written from scratch.

**Comment by freeekanayaka** [comment]
As stated in the [README](https://github.com/canonical/raft#credits), the code in this library was inspired by several other Raft implementations, including Willem's one (which is cited there). And being all of them implementations of the Raft algorithm described in Ongaro's dissertation they all have of course much in common (naming, logic, etc).

**Comment by kindofblue** [comment]
Never mind, I mistaken someone else's forks as this one.  Sorry for the mistake. BTW, great library.
