### ISSUE TITLE
Crashed followers sometimes fail to rejoin

### ISSUE THREAD

**Issue by j-e10** [canonical/raft#158]
I've experienced this on master but have ran into it in previous versions.

Steps to reproduce:

For convenience, add something like the following in `example/server.c`'s `serverTimerCb` so that it's obvious when it happens.

```
raft_id leader;
const char *addr;
raft_leader(&s->raft, &leader, &addr);
printf("id = %d leader = %lld\n", s->id, leader);
```

I tried to find the steps where it occurred the quickest but I have ran into it with the current defaults used in the example. Step 5 isn't strictly necessary to reproduce this.

1. `cd example`
2. Run 3 instances until one is a leader:
`ID=1; mkdir -p r$ID; LD_LIBRARY_PATH=../.libs ./server r$ID $ID` for `ID=1,2,3`
3. Pick a server X that is currently a follower
4. Terminate X with `ctrl+c` or `kill -9`
5. Wait (~5 seconds).
6. Re-execute X
7. If you see `leader != 0`, repeat from step 4.

It takes a bit of tries (usually fewer than 10).

Eventually, X is running again and instead of joining the other two, it seems to go off and start its own elections (from what I saw after enabling `tracef` in `tick.c`).

From this point on, X never rejoins the others (regardless of restarting X or wiping X's raft directory before re-executing it) until the current leader is manually restarted.

This also happens in the case where in step 6, you wipe X's raft directory just before re-executing it (which I think also makes it occur even more frequently).

**Comment by j-e10** [comment]
I think it's due to this TODO: https://github.com/canonical/raft/blob/v0.9.25/src/progress.c#L129

Changing the body to something like the below seems to prevent the issue from occurring. Whether it's correct / efficient, I'm not sure.

```
if (needs_heartbeat) {
    progressToProbe(r, 1);
    result = true;
} else {
    result = false;
}
```

**Comment by MathieuBordere** [comment]
Hi @j-e10 The TODO in https://github.com/canonical/raft/blob/v0.9.25/src/progress.c#L129 has been implemented recently, can you confirm the issue has been resolved for you?

**Comment by j-e10** [comment]
I have not been able to reproduce the issue using tag v0.10.0. Thank you for implementing this.
