### ISSUE TITLE
Raft snapshots take up a lot of disk space

### ISSUE THREAD

**Issue by MathieuBordere** [canonical/raft#198]
@freeekanayaka dqlite has users with pretty large DB's (+1GB) whose snapshots take up a lot of room. We have seen issues with slow storage devices that crumble under the I/O load of the frequent writing of these snapshots when there are a lot of writes to the DB. This results in writes to the DB sometimes taking over 30s to complete.

My proposal would be to compress the snapshots (lz4) before writing them to disk, this will not fix a slow storage device, but should at least alleviate a lot of the pressure on it. The compression can be done in raft itself or through the `fsm` methods that provide the snapshots to raft. My feeling is that it's the most convenient to do this in raft itself.

What are your thoughts on this?

**Comment by freeekanayaka** [comment]
Is it possible to get some insight about what data those users store into their DBs to make them grow as large as a GB? Gut feeling is that there might room for some mix approach where part of the data gets stored outside dqlite.

Regarding the compression approach, do you have access to sample snapshots and have an idea of how much they would compress with (say) lz4?

**Comment by MathieuBordere** [comment]
Depending on the speed of the compressions chosen, they compress between 8/1 and 12/1 ratio which is pretty good. It's just 1 particular microk8s user that I know of that has this issue, but there are/will be probably more, not sure if they can store data elsewhere.

**Comment by freeekanayaka** [comment]
> Depending on the speed of the compression chosen, they compress between 8/1 and 12/1 ratio which is pretty good. It's just 1 particular microk8s user that I know of that has this issue, but there are/will be probably more, not sure if they can store data elsewhere.

I see. That's a good compression ratio, if that would be enough to solve this particular issue, it's probably ok. However I guess it will only become clear once implemented. Maybe a more generic solution would be to introduce some way to "throttle" the speed at which snapshot are being written, so they don't disrupt too much the normal flow of raft entries.

**Comment by MathieuBordere** [comment]
Throttling the speed could also work. Luckily for me, I have a crappy ssd drive that starts to show that behavior after a while, I'll try both approaches and see which appears to work best.

**Comment by freeekanayaka** [comment]
> Throttling the speed could also work. Luckily for me, I have a crappy ssd drive that starts to show that behavior after a while, I'll try both approaches and see which one appears to work best.

FWIW throttling could be done by writing the snapshot in chunks (as opposed to a single pass) and waiting a bit between each chunk write. Ideally how much to wait would be decided by taking the current "load" of the disk into account, but probably some hard-coded value like a few hundred milliseconds might work ok.

The advantage of throttling is that you don't have to change the on-disk format and also you should be able to scale better (say you have a 10GB disk, then compression might stop helping). Of course the downside is that it might be a bit more complex to implement.

**Comment by MathieuBordere** [comment]
While introducing compression I will also tackle https://github.com/canonical/raft/issues/201, lz4 has an option to perform a crc check.
