### ISSUE TITLE
example/server failed to start after killing

### ISSUE THREAD

**Issue by zouyonghao** [canonical/raft#199]
Hi, all
I manually started 3 nodes of example/server, and try to kill/restart them all together several times with `killall`.

Then it sometimes failed to start with following logs:
```
1: starting
2: raft_start(): io: last entry on disk has index 389, which is behind last snapshot's index 345408
2: stopping
1: raft_start(): io: last entry on disk has index 389, which is behind last snapshot's index 345408
1: stopping
```

**Comment by MathieuBordere** [comment]
Thanks, we'll look into it.

**Comment by MathieuBordere** [comment]
Should be fixed by https://github.com/canonical/raft/pull/218.
