### ISSUE TITLE
Add crc data checksum to uv Snapshot 

### ISSUE THREAD

**Issue by MathieuBordere** [canonical/raft#201]
If I'm not mistaken we calculate crc checksums for the `snapshot.meta` and `segment` files, but perform no integrity checking on the `snapshot` data files. This should be introduced to detect disk corruptions.

**Comment by freeekanayaka** [comment]
Do we have more specific data about the issues we saw? Like a copy of the `data` directory of the broken deployment (or at least of the snapshot file)

**Comment by MathieuBordere** [comment]
Yes, we have one. Not sure if I can share though (if you're interested), will check.

**Comment by freeekanayaka** [comment]
It's okay not share, I wouldn't have time to check it, just wondering if you have more details about what's wrong with the file, e.g. if you used a debugger to understand where SQLite fails when opening it (assuming that's what's happening).

**Comment by MathieuBordere** [comment]
This is when trying to load the latest snapshot, the oldest snapshot is fine and is also +- 0.7MB bigger (5.5MB vs 4.8MB not necessarily relevant info).

**Comment by freeekanayaka** [comment]
Interesting that a couple of rows where returned, so the file is not complete garbage. I guess the database schema is not corrupted? `SELECT * FROM sqlite_master WHERE type='table'` or something like that.

**Comment by MathieuBordere** [comment]
Yes, that runs fine.

**Comment by MathieuBordere** [comment]
Checksum has been added as part of https://github.com/canonical/raft/pull/207.
