### ISSUE TITLE
Candidate reverts to follower during raft_transfer with pre_vote on

### ISSUE THREAD

**Issue by MathieuBordere** [canonical/raft#203]
Below some debug logging, basically server 1 wants to transfer leadership to 2 through `raft_transfer`, server 2 receives the TimeoutNow message, becomes candidate, doesn't increase it's term due to `pre_vote`, receives a heartbeat from 1 and converts back to follower, nullifying the effect of the attempted leadership transfer.

```
raft_transfer self:1 to:2        
self:2 recv message:6 from:1 state:1 term:1
recvTimeoutNow:28
convertSetState id:2 new_state:2
electionStart:114
self:3 recv message:1 from:1 state:1 term:1
self:4 recv message:1 from:1 state:1 term:1
self:1 recv message:2 from:3 state:3 term:1
self:1 recv message:2 from:4 state:3 term:1
self:2 recv message:1 from:1 state:2 term:1
convertSetState id:2 new_state:1
```

**Comment by MathieuBordere** [comment]
@freeekanayaka Should we just ignore the pre-vote step on a `raft_transfer` i.e. when `disrupt_leader` is set? The user specifically asked to transfer leadership, assuming that this was deliberate and the user knows what he's doing, we could skip the pre-vote logic no?

**Comment by freeekanayaka** [comment]
> @freeekanayaka Should we just ignore the pre-vote step on a `raft_transfer` i.e. when `disrupt_leader` is set? The user specifically asked to transfer leadership, assuming that this was deliberate and the user knows what he's doing, we could skip the pre-vote logic no?

Yeah I guess it'd make sense.
