### ISSUE TITLE
Slow snapshot can hang eventloop thread

### ISSUE THREAD

**Issue by MathieuBordere** [canonical/raft#222]
https://github.com/canonical/raft/blob/c15a5d247191b096d56f418a3a93b18c4f49a00e/src/replication.c#L1453 with large (1.5GiB) dqlite databases can hang the eventloop for 800-900ms (on my system).

**Comment by calvin2021y** [comment]
snapshot should be execute by async with a callback.  

User can choice to do the work in same thread or by uv_work_t, or create a new thread.

**Comment by MathieuBordere** [comment]
It's not as simple as just moving the work to a thread, we need to snapshot the state of the database and write it to disk without taking into account changes to the database that happen in meanwhile. It's the copying (memcpy) of the state of the database that takes all the time and happens in the main loop because then we are sure the database is not changing underneath us. I'm looking to take snapshots with copy-on-write behavior using more or less what's described here https://stackoverflow.com/questions/10998943/get-the-copy-on-write-behaviour-of-forking-without-fork.

In that way, we could take a 'quick' snapshot in the main loop without all the `memcpy` work and write it to disk without worrying that the data in meanwhile has changed.

**Comment by calvin2021y** [comment]
I find dqlite design is not suit for my use case, so I plan to use raft without dqlite.

On my design the sanpshot can be take from other thread without block main event loop,  that is why I ask for this. (it is like copy-on-write solution)

**Comment by MathieuBordere** [comment]
For now we will monitor the dqlite improvement in https://github.com/canonical/dqlite/pull/356 and reopen asynchronous snapshots https://github.com/canonical/raft/pull/268 when truly needed.
