### ISSUE TITLE
libuv API misuse

### ISSUE THREAD

**Issue by MathieuBordere** [canonical/raft#224]
```
Aug 02 08:17:25 soetomodb2 microk8s.daemon-apiserver[15684]: kube-apiserver: src/unix/poll.c:109: uv_poll_stop: Assertion `!uv__is_closing(handle)' failed.
Aug 02 08:17:26 soetomodb2 systemd[1]: snap.microk8s.daemon-apiserver.service: Main process exited, code=killed, status=6/ABRT
```

Possibly https://github.com/canonical/raft/blob/b71e3038944b34bed650c3612bfbe07f01ea6aa7/src/uv_writer.c#L379 is hit when the fd is already closed, triggering the assertion in https://github.com/libuv/libuv/blob/04289fa326b790c1a4abb236d1f9d913bacfc8c6/src/unix/poll.c#L113

Also see https://github.com/ubuntu/microk8s/issues/2487

**Comment by pedroleaoc** [comment]
Closing this one for now.
