### ISSUE TITLE
self elect term problem

### ISSUE THREAD

**Issue by chucongqing** [canonical/raft#227]
according to the raft paper. when a server turn to a candidate, it will increase it's term.

but  self elect mechanism  when there is only one voter (itself), raft didn't increase it's term.  It will cause some term checking problem when you start a single node then add more node. 

convert.c  line166 

Is this a  problem, or It's just my misunderstanding.

**Comment by MathieuBordere** [comment]
Thanks for your question, I'll come back to you with a reply in due time.

**Comment by MathieuBordere** [comment]
First of all, my excuses for the late response.

It is not a problem when you start a single server and add more nodes, in our case we bootstrap [0], [1]] the first node that has a ,setting its term to 1, other nodes are then added to the first node's configuration, but they are not bootstrapped upon startup, their term remains 0. When they receive a heartbeat from the original bootstrapping node, they will correctly identify it as a leader for term 1.

[0] https://github.com/canonical/raft/blob/042e0ca95c8454cfb6f6d064fb063d2dbace9df0/src/raft.c#L153
[1] https://github.com/canonical/raft/blob/042e0ca95c8454cfb6f6d064fb063d2dbace9df0/src/uv.c#L515
