### ISSUE TITLE
support send snapshot by patch mode

### ISSUE THREAD

**Issue by calvin2021y** [canonical/raft#230]
To avoid send large snapshot, we can use tools like bsdiff to generate patch for  snapshot,  and each node need keep some  snapshot index to generate the patch.

on all RPC results message need add  the node snapshot index list.  (number array)

When leader send snapshot install rpc,  use the follower's snapshot index list find a recent local snapshot, then made a bsdiff patch.  the install snapshot RCP should include the selected local  snapshot index.   

The follower will apply the patch with they own local snapshot, then restore the pached snapshot.

And a option to set how many snapshot should keep. 
 
This should be a options function so people can disable it,  if enabled they should provide a patch/apply_patch callback into FSM. (and this callback should be exec from uv_worker)

**Comment by MathieuBordere** [comment]
Thanks for the suggestion. raft is surely going to need some way to decrease the size of the `InstallSnapshot` RPC in the future, another option would be to send the snapshots in chunks over the wire.

regarding `bsdiff`, in the manpage:
```
BSDIFF(1)                                                                      BSD General Commands Manual                                                                      BSDIFF(1)

NAME
     bsdiff — generate a patch between two binary files

SYNOPSIS
     bsdiff ⟨oldfile⟩ ⟨newfile⟩ ⟨patchfile⟩

DESCRIPTION
     bsdiff compares ⟨oldfile⟩ to ⟨newfile⟩ and writes to ⟨patchfile⟩ a binary patch suitable for use by bspatch(1).  When ⟨oldfile⟩ and ⟨newfile⟩ are two versions of an executable pro‐
     gram, the patches produced are on average a factor of five smaller than those produced by any other binary patch tool known to the author.

     bsdiff uses memory equal to 17 times the size of ⟨oldfile⟩, and requires an absolute minimum working set size of 8 times the size of oldfile.

SEE ALSO
     bspatch(1)

AUTHORS
     Colin Percival <cperciva@freebsd.org>

FreeBSD                                                                                May 18, 2003                                                                               FreeBSD
```

The fact that bsdiff would use memory 17! times the size of `oldfile` will be problematic, but the idea to generate a diff could be interesting.
