### ISSUE TITLE
src/uv_writer.c:370: UvWriterClose: Assertion `!w->closing' failed

### ISSUE THREAD

**Issue by tomponline** [canonical/raft#245]
https://jenkins.linuxcontainers.org/job/lxd-github-pull-test/5139/arch=arm64,backend=dir,compiler=golang-1.16/console#console-section-5

```
/lxc-ci/build/tmp.KQmG1cbVOF/go/bin/lxc copy c1 c2 --refresh --instance-only --verbose
lxd: src/uv_writer.c:370: UvWriterClose: Assertion `!w->closing' failed.
Error: Put "http://unix.socket/1.0/instances/c2": EOF
```

**Comment by MathieuBordere** [comment]
I hope https://github.com/canonical/raft/pull/265 fixes this one, if it doesn't occur in the lxd test suite for a while after this PR is merged, I will close this issue.

**Comment by MathieuBordere** [comment]
This issue appeared before that PR, but the PR seems to make it occur more often (at least I was able to reproduce it, before I wasn't).

**Comment by freeekanayaka** [comment]
Ah I see, good that the PR made it more evident then.

**Comment by MathieuBordere** [comment]
@tomponline Have you seen this one since then?

**Comment by tomponline** [comment]
Not that ive been aware of, but not been looking out for it particularly.

**Comment by MathieuBordere** [comment]
Will close for now, happy to reopen if it pops up again.
