### ISSUE TITLE
membership rollback issue

### ISSUE THREAD

**Issue by as58545652** [canonical/raft#250]
https://github.com/canonical/raft/blob/ad00295ee0557b9ec974d035a4ef880e145c0e40/src/membership.c#L160

The assertion may fail if the configuration entry has already been removed. In addition, an uncommitted configuration may be stored in a snapshot, making it impossible to roll back.

**Comment by as58545652** [comment]
One possible solution would be to take a snapshot only if there is no uncommitted configuration, and to restore the configuration from the snapshot if there is no configuration entry in the log.

**Comment by MathieuBordere** [comment]
Thanks for this, will investigate.

**Comment by as58545652** [comment]
https://github.com/canonical/raft/blob/cbb9cd7ec16c758828b118c4c0260a651c2ac002/src/start.c#L16-L87

The most recent configuration might not be a committed one, which would probably lead to another membership rollback issue.

**Comment by MathieuBordere** [comment]
> One possible solution would be to take a snapshot only if there is no uncommitted configuration, and to restore the configuration from the snapshot if there is no configuration entry in the log.

There are degenerate cases where not taking a snapshot while there's an uncommitted configuration could lead to never taking a snapshot anymore.

There's this fragment in the [raft dissertation](https://raw.githubusercontent.com/ongardie/dissertation/master/online.pdf) in Chapter 5 
```
Raft also retains the latest configuration from the discarded log prefix in order to support cluster
membership changes.
```
In think the straightforward solution is to save the last known configuration when taking a snapshot so that it can be restored.

**Comment by as58545652** [comment]
> > One possible solution would be to take a snapshot only if there is no uncommitted configuration, and to restore the configuration from the snapshot if there is no configuration entry in the log.
> 
> There are degenerate cases where not taking a snapshot while there's an uncommitted configuration could lead to never taking a snapshot anymore.
> 
> There's this fragment in the [raft dissertation](https://raw.githubusercontent.com/ongardie/dissertation/master/online.pdf) in Chapter 5
> 
> ```
> Raft also retains the latest configuration from the discarded log prefix in order to support cluster
> membership changes.
> ```
> 
> In think the straightforward solution is to save the last known configuration when taking a snapshot so that it can be restored.

If there is an uncommitted configuration, it means the applied_index will not be able to reach beyond the index of that configuration change, and a snapshot cannot be taken beyond the applied_index. Therefore, an uncommitted configuration can still stand in the way of taking a snapshot.

**Comment by as58545652** [comment]
> > One possible solution would be to take a snapshot only if there is no uncommitted configuration, and to restore the configuration from the snapshot if there is no configuration entry in the log.
> 
> There are degenerate cases where not taking a snapshot while there's an uncommitted configuration could lead to never taking a snapshot anymore.
> 
> There's this fragment in the [raft dissertation](https://raw.githubusercontent.com/ongardie/dissertation/master/online.pdf) in Chapter 5
> 
> ```
> Raft also retains the latest configuration from the discarded log prefix in order to support cluster
> membership changes.
> ```
> 
> In think the straightforward solution is to save the last known configuration when taking a snapshot so that it can be restored.

Yeah, I think you might be right. We just need to save the previous configuration if there is an uncommitted one when taking a snapshot. But I have to say that an uncommitted configuration could still stand in the way because a snapshot can never be taken beyond any uncommitted index.
