### ISSUE TITLE
LGPL-3.0-or-later or LGPL-3.0-only clarification

### ISSUE THREAD

**Issue by jlovejoy** [canonical/raft#252]
Is this intended to be under LGPL-3.0-or-later or LGPL-3.0-only - with the linking exception? I can't find anything that specifies the 'only' or 'or later' option.

Maybe you could use SPDX identifiers in your source code :) which would be one of (depending on answer above):
```
SPDX-License-Identifier: LGPL-3.0-or-later WITH LGPL-3.0-linking-exception
SPDX-License-Identifier: LGPL-3.0-only WITH LGPL-3.0-linking-exception
```

**Comment by stgraber** [comment]
I thought that copies of the LGPLv3 which do not include the "or later" part are implicitly the "only" version which is the intent here.

**Comment by jlovejoy** [comment]
Thanks @stgraber !
