### ISSUE TITLE
different architectures support

### ISSUE THREAD

**Issue by gcsideal** [canonical/raft#258]
I'm packaging dqlite for Debian. I'm not sure what the targeted architectures are.
On i386 self-testing fails with (maybe it's not for 32 bit CPUs?):
test/unit/test_compress.c:47: Failed to allocate 2357198848 bytes

Other architectures fail with:
test/integration/test_uv_init.c:156: assertion failed: _rv == 1 (0 == 1)

Should I limit the supported architectures list? When is the next release scheduled to be released?

**Comment by stgraber** [comment]
Are you packaging a particular tag or master?

The Debian packages in our PPA seem to be behaving: https://launchpad.net/~dqlite/+archive/ubuntu/dev/+packages

**Comment by gcsideal** [comment]
> Are you packaging a particular tag or master?

Packaged 0.9.25 and it was quite OK for all architectures. Tried 0.11.1 and it was failing on most architectures. Then tried ad00295ee0557b9ec974d035a4ef880e145c0e40 and it was built only on ppc64el. Current master (456fd203c98f6edca91e9b272cd01e6a5569fdb9) tried only on i386 and amd64. It fails on the former and builds on the latter.

**Comment by stgraber** [comment]
That's odd, we automatically build packages for master and have it building and running tests on all arches here.

**Comment by ganto** [comment]
I once reported a similar issue in #156. The `test_uv_init.c` error could be triggered by building on a tmpfs, I therefore had to disable this test for a while on Fedora (https://github.com/ganto/copr-lxc4/commit/ea5494791f093c2a65df6b2f26eb601d203830b5)

**Comment by gcsideal** [comment]
> I once reported a similar issue in #156. The `test_uv_init.c` error could be triggered by building on a tmpfs, I therefore had to disable this test for a while on Fedora ([ganto/copr-lxc4@ea54947](https://github.com/ganto/copr-lxc4/commit/ea5494791f093c2a65df6b2f26eb601d203830b5))

That helped, thank you! Still fails on i386 and mipsel due to:
Error: test/unit/test_compress.c:47: Failed to allocate 2357198848 bytes.
Error: child killed by signal 6 (Aborted)

May you know a solution for this?

**Comment by gcsideal** [comment]
> That's odd, we automatically build packages for master and have it building and running tests on all arches here.

Turned out that Debian buildd's work on tmpfs while Launchpad uses normal disk space. I still have a build failure due to memory allocation on mipsel and i386. As I see, you don't build for these architectures. Do you plan to? Should I bisect when the problem appeared?

**Comment by MathieuBordere** [comment]
I don't think we're planning to build for mipsel and i386. It seems like on those architectures, the allocator cannot allocate a buffer larger than `INT_MAX`, `2147483647` on most 32-bit systems, and would in practice mean that the size of the database is restricted to 2GB.

**Comment by stgraber** [comment]
We build for i386. We however indeed do not build for any of the MIPS architectures.

**Comment by gcsideal** [comment]
> We build for i386.

Can you point me towards the build log / buildinfo for the i386 architecture? Packaged 0.11.3 and it still fails to build on Debian/Sid i386 for the very same reason. Wondering how you can build it.

**Comment by stgraber** [comment]
https://launchpad.net/~dqlite/+archive/ubuntu/dev/+packages

**Comment by stgraber** [comment]
Ubuntu dropped support for i386 a little while ago so you'll only find builds for it on bionic in that list.
