### ISSUE TITLE
Test failed for armhfp: aio.c:53: (*__errno_location ()) == 11 (38 == 11)

### ISSUE THREAD

**Issue by ganto** [canonical/raft#262]
Since the release of raft-0.11.3 the Fedora builds ([COPR](https://copr.fedorainfracloud.org/coprs/ganto/lxc4/build/3323799/) and [Koji](https://koji.fedoraproject.org/koji/packageinfo?packageID=34666)) for the armhfp architecture fail the test suite with the following error:
```
UvWriterInit/noResources                                    [ ERROR ]
Error: test/lib/aio.c:53: assertion failed: (*__errno_location ()) == 11 (38 == 11)
qemu: uncaught target signal 6 (Aborted) - core dumped
Error: child killed by signal 6 (Aborted)
```
Note that the built is run on a x86_64 machine with arm emulation through qemu.

@gcsideal is your Debian armhf build working? Do you build natively?

**Comment by gcsideal** [comment]
Hi @ganto,

> @gcsideal is your Debian armhf build working? Do you build natively?

 Yup, raft release 0.11.3 builds fine on armhf [1]. I don't know the HW details as the host is restricted [2], but I'm pretty sure it's a real armhf host.
[1] https://buildd.debian.org/status/logs.php?pkg=raft&arch=armhf
[2] https://db.debian.org/machines.cgi?host=arm-ubc-05

**Comment by ganto** [comment]
The code path was introduced with #254 asserting that if an error to the syscall happens it must be EAGAIN (11). In my case I get a ENOSYS (38) which looks like it might be somehow related to the arm emulation. 

But I wonder if the emulation is the cause of it, how could this work before where the syscall return value was directly asserted with 0.

**Comment by ganto** [comment]
Unfortunately I couldn't reproduce this error locally. But after reverting a520dd6601ee7f9bb1662816f494b9ff9ad0a257 that was the culprit in #263 this error also no longer happens in COPR or Koji.
