### ISSUE TITLE
Socket binding issue inside containers

### ISSUE THREAD

**Issue by ralight** [canonical/raft#273]
Hello,

Thanks for a very handy library.

I'm running into a problem when trying to run my application that uses raft inside a container. Calling `raft_init(..., "192.168.1.1:8080")` doesn't work because the container IP address is not the same as the external IP address. I tried using `raft_init(..., "0.0.0.0:8080")` and that worked when running multiple local instances outside of a container, but not inside the container.

I got a working result with this patch:

```
diff --git a/src/uv_tcp_listen.c b/src/uv_tcp_listen.c
index d11f84b..1386af4 100644
--- a/src/uv_tcp_listen.c
+++ b/src/uv_tcp_listen.c
@@ -284,7 +284,7 @@ int UvTcpListen(struct raft_uv_transport *transport, raft_uv_accept_cb cb)
     t = transport->impl;
     t->accept_cb = cb;
 
-    rv = uvIpParse(address, &addr);
+    rv = uvIpParse("0.0.0.0:8080", &addr);
     if (rv != 0) {
         return rv;
     }
```

This binds the listener to 0.0.0.0:8080, which means the port can happily be mapped to, and the server address of 192.168.1.1 is still available internally for the rest of the library.

I recognise this isn't a useful solution at the moment. I did consider making a modified version of `uvIpParse()` that would ignore the host part, but wanted your thoughts on this. I can see that some people would want to to be able to bind to a specific interface address so changing to using 0.0.0.0 across the board isn't great.

Perhaps there could be an option to set a bind address to be called before `raft_init()`. When `raft_init()` was called, it would use the bind address if set, otherwise use the address provided to `raft_init()`?

**Comment by freeekanayaka** [comment]
Glad you like the library!

I believe one solution would be to implement your own version of the `struct raft_uv_transport` interface. In particular, the `listen()` method would basically bind the `0.0.0.0` interface (or whatever you know the container will have). You can copy/paste most of the code from the stock `raft_uv_tcp_init` interface and just modify the few bits you need.

**Comment by freeekanayaka** [comment]
If we want to instead add the functionality of setting a custom bind address like @ralight suggests, perhaps we could add a function like `raft_uv_tcp_set_bind_address` (basically a custom method of the stock `raft_uv_transport` implementation), which should be called right after `raft_uv_tcp_init`.
