### ISSUE TITLE
Raft API redesign - include/raft/fixture.h (1/3)

### ISSUE THREAD

**Issue by MathieuBordere** [canonical/raft#288]
The goal is to redesign the API so that it is easily extensible in the future without breaking clients and without the need to bump the major soversion. I will create an issue for every single of the 3 exposed header files, this is the issue for

https://github.com/canonical/raft/blob/master/include/raft/fixture.h

I have taken over the header file below, removed some comments for brevity and added the changes I propose, that are the subject of this discussion, in between the code blocks.

```
/**
 * Raft cluster test fixture, using an in-memory @raft_io implementation. This
 * is meant to be used in unit tests.
 */

#ifndef RAFT_FIXTURE_H
#define RAFT_FIXTURE_H

#include "../raft.h"

#define RAFT_FIXTURE_MAX_SERVERS 8

/**
 * Fixture step event types.
 */
enum {
    RAFT_FIXTURE_TICK = 1, /* The tick callback has been invoked */
    RAFT_FIXTURE_NETWORK,  /* A network request has been sent or received */
    RAFT_FIXTURE_DISK,     /* An I/O request has been submitted */
    RAFT_FIXTURE_WORK      /* A large, CPU and/or memory intensive task */
};

/**
 * State of a single server in a cluster fixture.
 */
struct raft_fixture_server
{
    bool alive;                /* If false, the server is down. */
    raft_id id;                /* Server ID. */
    char address[16];          /* Server address (stringified ID). */
    struct raft_tracer tracer; /* Tracer. */
    struct raft_io io;         /* In-memory raft_io implementation. */
    struct raft raft;          /* Raft instance. */
};
```
I would remove `struct raft_fixture_server` entirely from this public header, it's not used in any API function and the fields are not accessed by our tests. In case our users would depend on the fields being accessible I could write setters and getters for them, but I think that might be a waste of time.
```
/**
 * Information about a test cluster event triggered by the fixture.
 */
struct raft_fixture_event
{
    unsigned server_index; /* Index of the server the event occurred on. */
    int type;              /* Type of the event. */
};
```
The internals of `struct raft_fixture_event` can be hidden, the users don't generate events themselves, they just consume them. I would add accessor methods for `server_index` and `type` so that the user supplied callback (below) can still do its job.

```
/**
 * Event callback. See raft_fixture_hook().
 */
struct raft_fixture;
typedef void (*raft_fixture_event_cb)(struct raft_fixture *f,
                                      struct raft_fixture_event *event);

/**
 * Test implementation of a cluster of @n servers, each having a user-provided
 * FSM.
 *
 * The cluster can simulate network latency and time elapsed on individual
 * servers.
 *
 * Servers can be alive or dead. Network messages sent to dead servers are
 * dropped. Dead servers do not have their @raft_io_tick_cb callback invoked.
 *
 * Any two servers can be connected or disconnected. Network messages sent
 * between disconnected servers are dropped.
 */
struct raft_fixture
{
    raft_time time;                  /* Global time, common to all servers. */
    unsigned n;                      /* Number of servers. */
    raft_id leader_id;               /* ID of current leader, or 0 if none. */
    struct raft_log log;             /* Copy of current leader's log. */
    raft_index commit_index;         /* Current commit index on leader. */
    struct raft_fixture_event event; /* Last event occurred. */
    raft_fixture_event_cb hook;      /* Event callback. */
    struct raft_fixture_server servers[RAFT_FIXTURE_MAX_SERVERS];
};
```
I would again hide the internals of `struct raft_fixture`, write accessors for `commit_index` as the fields is written in one of our tests. Functions already exist to access fields like `time`, `n` and `leader_id`.

```
/**
 * !!! DEPRECATED users should use `raft_fixture_initialize`. !!!
 *
 * Initialize a raft cluster fixture with @n servers. Each server will use an
 * in-memory @raft_io implementation and one of the given @fsms. All servers
 * will be initially connected to one another, but they won't be bootstrapped or
 * started.
 */
__attribute__((deprecated("use raft_fixture_initialize")))
RAFT_API int raft_fixture_init(struct raft_fixture *f,
                               unsigned n,
                               struct raft_fsm *fsms);

/**
 * Initialize a raft cluster fixture. Servers can be added by using
 * `raft_fixture_grow`.
 */
RAFT_API int raft_fixture_initialize(struct raft_fixture *f);
```
I would replace this with something like `raft_fixture_create` and `raft_fixture_destroy`, that creates the `struct raft_fixture` for the user and cleans it up. As the library itself allocates the `struct raft_fixture` we don't need to worry about size changes.

No other changes proposed after this point.
```
/**
 * Release all memory used by the fixture.
 */
RAFT_API void raft_fixture_close(struct raft_fixture *f);

/**
 * Convenience to generate a configuration object containing all servers in the
 * cluster. The first @n_voting servers will be voting ones.
 */
RAFT_API int raft_fixture_configuration(struct raft_fixture *f,
                                        unsigned n_voting,
                                        struct raft_configuration *conf);

/**
 * Convenience to bootstrap all servers in the cluster using the given
 * configuration.
 */
RAFT_API int raft_fixture_bootstrap(struct raft_fixture *f,
                                    struct raft_configuration *conf);

/**
 * Convenience to start all servers in the fixture.
 */
RAFT_API int raft_fixture_start(struct raft_fixture *f);

/**
 * Return the number of servers in the fixture.
 */
RAFT_API unsigned raft_fixture_n(struct raft_fixture *f);

/**
 * Return the current cluster global time. All raft instances see the same time.
 */
RAFT_API raft_time raft_fixture_time(struct raft_fixture *f);

/**
 * Return the raft instance associated with the @i'th server of the fixture.
 */
RAFT_API struct raft *raft_fixture_get(struct raft_fixture *f, unsigned i);

/**
 * Return @true if the @i'th server hasn't been killed.
 */
RAFT_API bool raft_fixture_alive(struct raft_fixture *f, unsigned i);

/**
 * Return the index of the current leader, or the current number of servers if
 * there's no leader.
 */
RAFT_API unsigned raft_fixture_leader_index(struct raft_fixture *f);

/**
 * Return the ID of the server the @i'th server has voted for, or zero .
 */
RAFT_API raft_id raft_fixture_voted_for(struct raft_fixture *f, unsigned i);

/**
 * Drive the cluster so the @i'th server gets elected as leader.
 *
 * This is achieved by bumping the randomized election timeout of all other
 * servers to a very high value, letting the one of the @i'th server expire and
 * then stepping the cluster until the election is won.
 *
 * There must currently be no leader and no candidate and the given server must
 * be a voting one. Also, the @i'th server must be connected to a majority of
 * voting servers.
 */
RAFT_API void raft_fixture_elect(struct raft_fixture *f, unsigned i);

/**
 * Drive the cluster so the current leader gets deposed.
 *
 * This is achieved by dropping all AppendEntries result messages sent by
 * followers to the leader, until the leader decides to step down because it has
 * lost connectivity to a majority of followers.
 */
RAFT_API void raft_fixture_depose(struct raft_fixture *f);

/**
 * Step through the cluster state advancing the time to the minimum value needed
 * for it to make progress.
 */
RAFT_API struct raft_fixture_event *raft_fixture_step(struct raft_fixture *f);

/**
 * Call raft_fixture_step() exactly @n times, and return the last event fired.
 */
RAFT_API struct raft_fixture_event *raft_fixture_step_n(struct raft_fixture *f,
                                                        unsigned n);

/**
 * Step the cluster until the given @stop function returns #true, or @max_msecs
 * have elapsed.
 *
 * Return #true if the @stop function has returned #true within @max_msecs.
 */
RAFT_API bool raft_fixture_step_until(struct raft_fixture *f,
                                      bool (*stop)(struct raft_fixture *f,
                                                   void *arg),
                                      void *arg,
                                      unsigned max_msecs);

/**
 * Step the cluster until @msecs have elapsed.
 */
RAFT_API void raft_fixture_step_until_elapsed(struct raft_fixture *f,
                                              unsigned msecs);

/**
 * Step the cluster until a leader is elected, or @max_msecs have elapsed.
 */
RAFT_API bool raft_fixture_step_until_has_leader(struct raft_fixture *f,
                                                 unsigned max_msecs);

/**
 * Step the cluster until the current leader gets deposed, or @max_msecs have
 * elapsed.
 */
RAFT_API bool raft_fixture_step_until_has_no_leader(struct raft_fixture *f,
                                                    unsigned max_msecs);

/**
 * Step the cluster until the @i'th server has applied the entry at the given
 * index, or @max_msecs have elapsed. If @i equals the number of servers, then
 * step until all servers have applied the given entry.
 */
RAFT_API bool raft_fixture_step_until_applied(struct raft_fixture *f,
                                              unsigned i,
                                              raft_index index,
                                              unsigned max_msecs);

/**
 * Step the cluster until the state of the @i'th server matches the given one,
 * or @max_msecs have elapsed.
 */
RAFT_API bool raft_fixture_step_until_state_is(struct raft_fixture *f,
                                               unsigned i,
                                               int state,
                                               unsigned max_msecs);

/**
 * Step the cluster until the term of the @i'th server matches the given one,
 * or @max_msecs have elapsed.
 */
RAFT_API bool raft_fixture_step_until_term_is(struct raft_fixture *f,
                                              unsigned i,
                                              raft_term term,
                                              unsigned max_msecs);

/**
 * Step the cluster until the @i'th server has voted for the @j'th one, or
 * @max_msecs have elapsed.
 */
RAFT_API bool raft_fixture_step_until_voted_for(struct raft_fixture *f,
                                                unsigned i,
                                                unsigned j,
                                                unsigned max_msecs);

/**
 * Step the cluster until all pending network messages from the @i'th server to
 * the @j'th server have been delivered, or @max_msecs have elapsed.
 */
RAFT_API bool raft_fixture_step_until_delivered(struct raft_fixture *f,
                                                unsigned i,
                                                unsigned j,
                                                unsigned max_msecs);

/**
 * Set a function to be called after every time a fixture event occurs as
 * consequence of a step.
 */
RAFT_API void raft_fixture_hook(struct raft_fixture *f,
                                raft_fixture_event_cb hook);

/**
 * Disconnect the @i'th and the @j'th servers, so attempts to send a message
 * from @i to @j will fail with #RAFT_NOCONNECTION.
 */
RAFT_API void raft_fixture_disconnect(struct raft_fixture *f,
                                      unsigned i,
                                      unsigned j);

/**
 * Reconnect the @i'th and the @j'th servers, so attempts to send a message
 * from @i to @j will succeed again.
 */
RAFT_API void raft_fixture_reconnect(struct raft_fixture *f,
                                     unsigned i,
                                     unsigned j);

/**
 * Saturate the connection between the @i'th and the @j'th servers, so messages
 * sent by @i to @j will be silently dropped.
 */
RAFT_API void raft_fixture_saturate(struct raft_fixture *f,
                                    unsigned i,
                                    unsigned j);

/**
 * Return true if the connection from the @i'th to the @j'th server has been set
 * as saturated.
 */
RAFT_API bool raft_fixture_saturated(struct raft_fixture *f,
                                     unsigned i,
                                     unsigned j);

/**
 * Desaturate the connection between the @i'th and the @j'th servers, so
 * messages sent by @i to @j will start being delivered again.
 */
RAFT_API void raft_fixture_desaturate(struct raft_fixture *f,
                                      unsigned i,
                                      unsigned j);

/**
 * Kill the server with the given index. The server won't receive any message
 * and its tick callback won't be invoked.
 */
RAFT_API void raft_fixture_kill(struct raft_fixture *f, unsigned i);

/**
 * Revive a killed server with the given index.
 */
RAFT_API void raft_fixture_revive(struct raft_fixture *f, unsigned i);

/**
 * Add a new empty server to the cluster and connect it to all others.
 */
RAFT_API int raft_fixture_grow(struct raft_fixture *f, struct raft_fsm *fsm);


RAFT_API void raft_fixture_set_randomized_election_timeout(
    struct raft_fixture *f,
    unsigned i,
    unsigned msecs);


RAFT_API void raft_fixture_set_network_latency(struct raft_fixture *f,
                                               unsigned i,
                                               unsigned msecs);


RAFT_API void raft_fixture_set_disk_latency(struct raft_fixture *f,
                                            unsigned i,
                                            unsigned msecs);


RAFT_API void raft_fixture_set_term(struct raft_fixture *f,
                                    unsigned i,
                                    raft_term term);


RAFT_API void raft_fixture_set_snapshot(struct raft_fixture *f,
                                        unsigned i,
                                        struct raft_snapshot *snapshot);


RAFT_API void raft_fixture_add_entry(struct raft_fixture *f,
                                     unsigned i,
                                     struct raft_entry *entry);


RAFT_API void raft_fixture_io_fault(struct raft_fixture *f,
                                    unsigned i,
                                    int delay,
                                    int repeat);

/**
 * Return the number of messages of the given type that the @i'th server has
 * successfully sent so far.
 */
RAFT_API unsigned raft_fixture_n_send(struct raft_fixture *f,
                                      unsigned i,
                                      int type);

RAFT_API unsigned raft_fixture_n_recv(struct raft_fixture *f,
                                      unsigned i,
                                      int type);

#endif /* RAFT_FIXTURE_H */
```

**Comment by freeekanayaka** [comment]
Ideally I'd like to see both of the following goals achieved:

1. Keep ABI compatibility across releases, even when some user-facing `struct` gets changed (e.g. adding fiends)
2. Offer users the possibility to do stack allocation and struct embedding.

We have discussed the need of 1., which is really what created problems so far, so we are all on the same page there.

Regarding 2., I believe that we all agree it has benefits and it's a nice to have, but not if it means to sacrifice 1. Please correct me, if you actually think 2. is a non-goal or even an anti-goal.

The way I see declarations in `.h` files is that they do not necessarily mean "anything declared here is public". Taking again `libuv` which is IMO a good example of well-designed C, we can see that they often document which `struct` declarations are public and which fields in those structs are public (if I remember correctly the stdlib an the kernel do the same occasionally).

This is a bit equivalent to Python's "We are all consenting adults here" philosophy.

Achieving 2. while preserving 1. is possible, although it has a slightly higher cost in terms of maintenance than making things private and preventing users from stack allocation/embedding, so YMMV.

With all the above in mind I'd suggest the changes below:

> ```
> /**
>  * Raft cluster test fixture, using an in-memory @raft_io implementation. This
>  * is meant to be used in unit tests.
>  */
> 
> #ifndef RAFT_FIXTURE_H
> #define RAFT_FIXTURE_H
> 
> #include "../raft.h"
> 
> #define RAFT_FIXTURE_MAX_SERVERS 8
> 
> /**
>  * Fixture step event types.
>  */
> enum {
>     RAFT_FIXTURE_TICK = 1, /* The tick callback has been invoked */
>     RAFT_FIXTURE_NETWORK,  /* A network request has been sent or received */
>     RAFT_FIXTURE_DISK,     /* An I/O request has been submitted */
>     RAFT_FIXTURE_WORK      /* A large, CPU and/or memory intensive task */
> };
> 
> /**
>  * State of a single server in a cluster fixture.
>  */
> struct raft_fixture_server
> {
>     bool alive;                /* If false, the server is down. */
>     raft_id id;                /* Server ID. */
>     char address[16];          /* Server address (stringified ID). */
>     struct raft_tracer tracer; /* Tracer. */
>     struct raft_io io;         /* In-memory raft_io implementation. */
>     struct raft raft;          /* Raft instance. */
> };
> ```
> 
> I would remove `struct raft_fixture_server` entirely from this public header, it's not used in any API function and the fields are not accessed by our tests. In case our users would depend on the fields being accessible I could write setters and getters for them, but I think that might be a waste of time.

I'd alternatively propose to leave only the declaration of `struct raft_fixture_server` but not its definition (which would be moved to `src/fixture.c`), then change the type of `struct raft_fixture->servers` from:

```C
struct raft_fixture
{
    // ...
    struct raft_fixture_server servers[RAFT_FIXTURE_MAX_SERVERS];
}
```

to

```C
struct raft_fixture {
    // ...
    struct raft_fixture_server* servers[RAFT_FIXTURE_MAX_SERVERS];
}
```

So if the internals of `struct raft_fixture_server` change, that has no impact on the size or layout of `struct raft_fixture`.

> 
> ```
> /**
>  * Information about a test cluster event triggered by the fixture.
>  */
> struct raft_fixture_event
> {
>     unsigned server_index; /* Index of the server the event occurred on. */
>     int type;              /* Type of the event. */
> };
> ```
> 
> The internals of `struct raft_fixture_event` can be hidden, the users don't generate events themselves, they just consume them. I would add accessor methods for `server_index` and `type` so that the user supplied callback (below) can still do it's job.

I'd alternatively propose an approach similar to `struct raft_fixture_server`, leaving the declaration of `struct raft_fixture_event` in the header, but not the definition. The `struct raft_fixture->event` field would need to be changed to be a pointer and be allocated dynamically, and we'd need to add the accessors for `server_index` and `type`, as you suggest.

> 
> ```
> /**
>  * Event callback. See raft_fixture_hook().
>  */
> struct raft_fixture;
> typedef void (*raft_fixture_event_cb)(struct raft_fixture *f,
>                                       struct raft_fixture_event *event);
> 
> /**
>  * Test implementation of a cluster of @n servers, each having a user-provided
>  * FSM.
>  *
>  * The cluster can simulate network latency and time elapsed on individual
>  * servers.
>  *
>  * Servers can be alive or dead. Network messages sent to dead servers are
>  * dropped. Dead servers do not have their @raft_io_tick_cb callback invoked.
>  *
>  * Any two servers can be connected or disconnected. Network messages sent
>  * between disconnected servers are dropped.
>  */
> struct raft_fixture
> {
>     raft_time time;                  /* Global time, common to all servers. */
>     unsigned n;                      /* Number of servers. */
>     raft_id leader_id;               /* ID of current leader, or 0 if none. */
>     struct raft_log log;             /* Copy of current leader's log. */
>     raft_index commit_index;         /* Current commit index on leader. */
>     struct raft_fixture_event event; /* Last event occurred. */
>     raft_fixture_event_cb hook;      /* Event callback. */
>     struct raft_fixture_server servers[RAFT_FIXTURE_MAX_SERVERS];
> };
> ```
> 
> I would again hide the internals of `struct raft_fixture`, write accessors for `commit_index` as the fields is written in one of our tests. Functions already exist to access fields like `time`, `n` and `leader_id`.

I'd alternatively propose to add a `version` field to `struct raft_fixture`, so it can still be embedded and/or be allocated on the stack. I'd also document which attributes are private and which are public. It's fine to have them all private and tell users that they must use accessors. I think we can have cases where we make a field public (possibly read-only) if it's really convenient for users to access it directly as opposed to calling an accessor each time. We can also have both sometimes.

> 
> ```
> /**
>  * !!! DEPRECATED users should use `raft_fixture_initialize`. !!!
>  *
>  * Initialize a raft cluster fixture with @n servers. Each server will use an
>  * in-memory @raft_io implementation and one of the given @fsms. All servers
>  * will be initially connected to one another, but they won't be bootstrapped or
>  * started.
>  */
> __attribute__((deprecated("use raft_fixture_initialize")))
> RAFT_API int raft_fixture_init(struct raft_fixture *f,
>                                unsigned n,
>                                struct raft_fsm *fsms);
> 
> /**
>  * Initialize a raft cluster fixture. Servers can be added by using
>  * `raft_fixture_grow`.
>  */
> RAFT_API int raft_fixture_initialize(struct raft_fixture *f);
> ```
> 
> I would replace this with something like `raft_fixture_create` and `raft_fixture_destroy`, that creates the `struct raft_fixture` for the user and cleans it up. As the library itself allocates the `struct raft_fixture` we don't need to worry about size changes.

I'd alternatively propose to change this back to `raft_fixture_init`, so the naming is consistent with the rest of the lib. With the `version` field in place, I think it does not matter much if we use the old signature (`raft_fixture_init(struct raft_fixture *f, unsigned n, struct raft_fsm *fsms)`) or the new one (`raft_fixture_init(struct raft_fixture *f)`), both would be fine.

**Comment by MathieuBordere** [comment]
> 1. Keep ABI compatibility across releases, even when some user-facing struct gets changed (e.g. adding fiends)
> 2. Offer users the possibility to do stack allocation and struct embedding.
> We have discussed the need of 1., which is really what created problems so far, so we are all on the same page there.
> 
> Regarding 2., I believe that we all agree it has benefits and it's a nice to have, but not if it means to sacrifice 1. Please correct me, if you actually think 2. is a non-goal or even an anti-goal.

Personally, I didn't consider 2 to be a goal, and I like hiding as much of the implementation as possible, but I'm less experienced than you so I don't mind trusting your judgement on this one.

> I'd alternatively propose to change this back to `raft_fixture_init`, so the naming is consistent with the rest of the lib. With the `version` field in place, I think it does not matter much if we use the old signature (`raft_fixture_init(struct raft_fixture *f, unsigned n, struct raft_fsm *fsms)`) or the new one (`raft_fixture_init(struct raft_fixture *f)`), both would be fine.

That's okay for me. I would however not use the old signature `raft_fixture_init(struct raft_fixture *f, unsigned n, struct raft_fsm *fsms)`, if the user allocates an array based on an old size, we are in trouble again. Yes, we could check the version of the first member and then based on the past size, stride through the array, but it makes matters needlessly complicated.

Your suggestions are fine I think, thanks.

**Comment by stgraber** [comment]
I don't personally care too much about 2) but I'm also not a consumer of libraft myself.

@brauner can you weigh in on this one?

Specifically:

> Ideally I'd like to see both of the following goals achieved:
> 
>     1. Keep ABI compatibility across releases, even when some user-facing `struct` gets changed (e.g. adding fiends)
> 
>     2. Offer users the possibility to do stack allocation and struct embedding.
> 
> 
> We have discussed the need of 1., which is really what created problems so far, so we are all on the same page there.
> 
> Regarding 2., I believe that we all agree it has benefits and it's a nice to have, but not if it means to sacrifice 1. Please correct me, if you actually think 2. is a non-goal or even an anti-goal.
> 
> The way I see declarations in `.h` files is that they do not necessarily mean "anything declared here is public". Taking again `libuv` which is IMO a good example of well-designed C, we can see that they often document which `struct` declarations are public and which fields in those structs are public (if I remember correctly the stdlib an the kernel do the same occasionally).

And also on what's best practices wrt to versioning things. Currently the approach in libraft is to have an int version field at the beginning of the struct which is checked prior to accessing additional information.

I'm personally not a big fan of that because as we know, people like backports and having a simple increasing integer describe your API is likely to cause problems down the line.

I believe the current standard in kernel land is to provide a struct + struct len in all calls. The main downside is that we can't take things off of a struct, we can only append to it. But this doesn't prevent the deprecation of fields, they just won't be removed. Is that correct?

**Comment by freeekanayaka** [comment]
I believe version and and struct size are functionally equivalent, they are both a bit for static compile-time info that the client gives to the library. As long as fields are just added both approaches should work work the same (the size is monotonically increasing number, exactly like the version).

If fields are removed or repurposed the question is more complicated (in both cases), but I think we can just decide that we only add new fields, and at most deprecate old ones, as @stgraber hints.

All in all the choice between the two feels a matter of taste, unless I'm missing something.

**Comment by stgraber** [comment]
I can see pros and cons on both sides.

For the version int, I see:
[+] Allows for field removal
[+] Slightly lesser coupling between library and consumer
[-] Consumer needs to keep track of fields used and version needed for those
[-] Frequent version bumps are likely to annoy users

For the struct len approach:
[+] Foolproof on the consumer side, if you can set a field on the struct, it will be properly handled by the library
[-] No support for field removal
[-] Tighter coupling. Whatever version of the struct the consumer had at build time needs to be supported by runtime.

As a consumer, I'd prefer the struct len approach because of it being foolproof. I don't have to check headers and docs to figure out what the minimum version it is I need to set for it to work.

As an upstream, I think the struct len approach is also simpler. It makes it trivial to see if the consumer may be asking for things we don't support (compare size with our size, if larger, bail) while also making it easy to support older consumers either by knowing min-size for a particular field or by copying the struct and initializing the unspecified fields with default values.

**Comment by freeekanayaka** [comment]
As for frequent version bumps, I was assuming the idiomatic way would for a client to set the version would be using something like `RAFT_FIXTURE_VERSION`, which would basically be the equivalent of `sizeof struct raft_fixture`. Both would be the compile-time "default" that the client would use. So when you recompile against a newer version you are automatically "upgraded" to the new version without any code change on the client side (that happens both for the version approach and for the size approach), newly added fields of course get initialized with defaults as you mention.

The above also implies the foolproof propert: if you use `RAFT_FIXTURE_VERSION` in your client, whatever field is there in `struct raft_version` at the time you compile, you can be sure it will be supported by newer versions of the lib.

That is what I was meaning with the two approaches being equivalent, in both cases you have an integer that is automatically set for the client at compile time (either `RAFT_FIXTURE_VERSION` or `sizeof struct raft_fixture`) and that is associated with the layout of the struct declared in the `.h` at the time the client was compiled.

That being said, given that we are not going to support field removals or rearrangement, I believe it's fine either way, so ok for the struct len if it's going to be more "conventional" or familiar for folks or to us.

**Comment by MathieuBordere** [comment]
So in that case, we would extend `raft_fixture_init` to take a version (or size) argument, which is a compile time constant, that is then set on the struct in the init function, in order for other functions to access the fields safely. Passing the version or size to `raft_fixture_init` would force the user to not forget to set it. (Excuse me if I'm stating the obvious here)

**Comment by freeekanayaka** [comment]
That's a relatively common strategy indeed, afaik. That works for me, since goals 1. and 2. are both achieved, there's no burden on the user, and less burden on the lib compared to the version/size approach.

Of course the tradeoff is that you might eventually run of out of padding and then we'll have to break the ABI and bump sover, but if the padding is reasonably large that moment should be reasonably far in the future. I'm personally fine with that tradeoff.

I also believe that the churn/rate-of-change of libraft (especially in terms of struct definitions) won't be so dramatic that either padding or version/size will be annoying, i.e. padding should not run out so fast and also structs shouldn't change so much that the additional burden of version/size becomes problematic. So I'm basically fine with whichever of these three options feels better to to you, perhaps with a slight preference to padding given its simplicity (at the cost of the tradeoff).
