### ISSUE TITLE
./test/integration/uv tcp_connect/closeDuringHandshake broken with libuv-1.44.2

### ISSUE THREAD

**Issue by wentasah** [canonical/raft#292]
A NixOS user [reported a test failure](https://github.com/NixOS/nixpkgs/issues/183759), which happens with libuv-1.44.2, but with libuv-1.44.1 the test passes.

Test output:
```
tcp_connect/closeDuringHandshake                            [ FAIL  ]
Error: test/integration/test_uv_tcp_connect.c:46: assertion failed: status == result->status (0 == 13)
```
Relevant output of `strace ./test/integration/uv tcp_connect/closeDuringHandshake --no-fork`:
```
socket(AF_INET, SOCK_STREAM|SOCK_CLOEXEC|SOCK_NONBLOCK, IPPROTO_IP) = 13
connect(13, {sa_family=AF_INET, sin_port=htons(41893), sin_addr=inet_addr("127.0.0.1")}, 16) = -1 EINPROGRESS (Operation now in progress)
epoll_ctl(5, EPOLL_CTL_ADD, 8, {events=EPOLLIN, data={u32=8, u64=8}}) = 0
epoll_ctl(5, EPOLL_CTL_ADD, 10, {events=EPOLLIN, data={u32=10, u64=10}}) = 0
epoll_ctl(5, EPOLL_CTL_ADD, 13, {events=EPOLLOUT, data={u32=13, u64=13}}) = 0
epoll_wait(5, [{events=EPOLLOUT, data={u32=13, u64=13}}], 1024, -1) = 1
getsockopt(13, SOL_SOCKET, SO_ERROR, [0], [4]) = 0
write(13, "\1\0\0\0\0\0\0\0\1\0\0\0\0\0\0\0\20\0\0\0\0\0\0\000127.0.0."..., 40) = 40
write(2, "Error", 5)                    = 5
write(2, ": ", 2)                       = 2
write(2, "test/integration/test_uv_tcp_con"..., 43) = 43
write(2, "assertion failed: status == resu"..., 52) = 52
```
From looking at [Libuv 1.44.2 changelog](https://github.com/libuv/libuv/releases/tag/v1.44.2), my uneducated guess is that https://github.com/libuv/libuv/pull/3598 might be the cause.

**Comment by wentasah** [comment]
I forgot to mention that the test failure happens both with the current master as well as with raft 0.11.2, which is in nixpkgs.

**Comment by MathieuBordere** [comment]
Thanks, I'll have a look, it's a bit of a lower priority right now, so please bear with me :-)

**Comment by gibmat** [comment]
A similar bug has been reported in Debian ([#1016311](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1016311)) which will cause a series of autorms in a little over a month. It would be great if a fix could be developed before that happens. (I care about this because raft is one of the dependencies for packaging LXD.)

**Comment by MathieuBordere** [comment]
Okay, will prioritize this one.
