### ISSUE TITLE
how to  compile and run raft-master/test

### ISSUE THREAD

**Issue by yml435** [canonical/raft#293]
I want to learn raft code by running these test cases in  raft-master/test. But please tell me how to compile and run. and what confiugre options need to be added. thanks.
I see that there are many comments in your code, such as "From Section 4.2.3". Which document does this mean, please? Can you please provide specific documents?

**Comment by MathieuBordere** [comment]
The document could mean 2 things, the [raft dissertation](https://web.stanford.edu/~ouster/cgi-bin/papers/OngaroPhD.pdf) or the [raft paper](https://raft.github.io/raft.pdf).

For running the test you could look at the [github workflow](https://github.com/canonical/raft/blob/master/.github/workflows/build-and-test.yml) but generally

There are no special flags needed for `configure` and you build and run the tests with `make check`. This will produce binaries that you can then also run individually e.g. in the folder `test/integration` you will find a binary `core` that you can run. These tests are build around [munit](https://nemequ.github.io/munit/), check the website to see how to run individual tests etc.
