### ISSUE TITLE
Assertion failure in progressShouldReplicate

### ISSUE THREAD

**Issue by cole-miller** [canonical/raft#314]
I noticed what looks like a significant assertion failure from raft while looking at the logs for a CI run of my jepsen.dqlite branch (https://github.com/canonical/jepsen.dqlite/pull/30). It's this one:

https://github.com/canonical/raft/blob/2b5c68b3755104410906608a391805d3adbafa11/src/progress.c#L116-L118

Here's the log: [app.log](https://github.com/canonical/raft/files/9636452/app.log). The CI job in question is [this one](https://github.com/canonical/jepsen.dqlite/actions/runs/3112903624/jobs/5046862594).

**Comment by MathieuBordere** [comment]
Looks pretty bad indeed.

**Comment by MathieuBordere** [comment]
Could be a variant of https://github.com/canonical/raft/pull/255

**Comment by cole-miller** [comment]
Continuing to see this in Jepsen logs (like the failures for [this run](https://github.com/canonical/jepsen.dqlite/actions/runs/3135849145)). It seems to be triggered by the combination of the "bank" workload and the disk nemesis, which offers some clues to what could be going wrong:

- probably a disk write failure is not being handled properly somewhere
- our handling of transactions is probably implicated (though note that the "append" workload also uses transactions, and I haven't seen this assertion fire on that workload yet)

**Comment by MathieuBordere** [comment]
The initial proposal to shut down the node upon seeing an I/O failure could possibly fix this.

**Comment by cole-miller** [comment]
Yeah, later today I'll try opening a PR with that approach (crashing on disk write failure) and see if it improves the situation.

**Comment by MathieuBordere** [comment]
I wonder what makes it trigger in your PR though.
