### ISSUE TITLE
Partially-replicated entries after a disk write failure

### ISSUE THREAD

**Issue by cole-miller** [canonical/raft#320]
Consider this sequence of events:

1. A raft leader gets an append request. It starts a disk write for the new entry X and, concurrently, replicates X to its followers.
2. A follower receives the entry X and appends it to its log.
3. The leader's disk write fails, and it truncates its log, erasing X.
4. Later, the same leader (in the same term) gets another append request. It appends an entry Y at the same index that X previously occupied and replicates it.
5. The same follower receives the entry Y. Since it already has an entry with the same index/term, it responds with success to the leader *without* updating its log to replace X with Y.
6. Now, the leader can commit Y, but the follower in question will apply X to its state machine instead -- bad!

To fix this, either leaders need to wait until disk writes succeed to replicate the corresponding entries (as I believe the whitepaper envisions), or followers need to replace log entries more aggressively.

**Comment by freeekanayaka** [comment]
I'd say that in case of disk failure writing entry X the leader should step down or something equivalent. The case is rare enough that it's better to optimize for the common case instead of (for example) delaying replication of an entry until the disk write succeeds.

**Comment by freeekanayaka** [comment]
> That would certainly simplify things. The leader should step down _after_ communicating the I/O error to the client's callback, right?

Does it make a difference? BTW technically speaking this is a situation that won't be handled that well by the client anyways, because client sessions, request IDs and retries are not yet implemented (see the "Client sessions" section in https://dqlite.io/docs/explanation/replication and the Raft dissertation).

> And we should pick a follower to be the new leader (as in raft_transfer) rather than waiting for an election timeout?

I believe that the case is rare enough that letting the timeout kick in is ok, and no particular optimization is needed. It will be a matter of a few hundred milliseconds.

**Comment by freeekanayaka** [comment]
> > BTW technically speaking this is a situation that won't be handled that well by the client anyways, because client sessions, request IDs and retries are not yet implemented (see the "Client sessions" section in https://dqlite.io/docs/explanation/replication and the Raft dissertation).
> 
> Indeed, I'm hoping to rectify that pretty soon.

That is probably going to be a significant chunk of work, but it is surely a nice to have.

> I think it's still better to give the client some kind of indication of what went wrong to aid debugging.

Yes, agreed. Probably we can step down right away and reply to the client after that. I don't believe we need to wait, unless I'm missing something.

> > I believe that the case is rare enough that letting the timeout kick in is ok, and no particular optimization is needed.
> 
> Ack
