### ISSUE TITLE
Double free in ioCloseCb

### ISSUE THREAD

**Issue by cole-miller** [canonical/raft#341]
See the log here: https://github.com/canonical/dqlite/actions/runs/3700630188/jobs/6269233919. Seems that ioCloseCb is getting invoked twice for the same `struct raft`.

https://github.com/canonical/raft/blob/faadebbe8fae5f7faf1f015b90fae094b3fec7e8/src/raft.c#L110

**Comment by calvin2021y** [comment]
maybe you can try:

1) add log when you start call uvMaybeFireCloseCb, and before return.

**Comment by pedroleaoc** [comment]
I will close this one for now due to lack of a reproducer.
