### ISSUE TITLE
0.17 releases?

### ISSUE THREAD

**Issue by juippis** [canonical/raft#370]
Hey, 

I noticed lxd-5.0.2 (just released) bundles raft-0.17.1. Then I saw this commit b4bdc8a8dc35557078102919190fd09746d6bad0. But I can't find the 0.17.0 or 0.17.1 release tarballs anywhere? So I wonder where are the releases made? :) 

(and if lxd-5.0.2 **requires** raft-0.17.1 it'll be a problem)

**Comment by juippis** [comment]
Thanks a lot!

**Comment by MathieuBordere** [comment]
@juippis Please also note that LXD doesn't build from Github releases, but builds directly from the raft master branch. It (shouldn't) matter in most cases, but if you want to build the exact same thing as what is built in LXD's snaps, this is something you should take into account.
