### ISSUE TITLE
[question] Meaning of server_id and server_address in raft_message struct

### ISSUE THREAD

**Issue by mdorier** [canonical/raft#379]
I'm implementing my own `raft_io` and I'm having a hard time understanding the exact meaning of the `server_id` and `server_address` fields in the `raft_message` structure. The comments indicate the following:

```
    raft_id server_id;          /* ID of sending or destination server. */
    const char *server_address; /* Address of sending or destination server. */
```

Does this mean that they should change on their way to their destination to reflect this meaning?

E.g. assuming we have processes A and B, is this the expected semantics of these fields:
- In process A a `raft_message` is created by raft, with `server_id = id of B` and `server_address = "B"` (i.e. the message contains information about the destination server), and passed to the `send` function.
- The `send` function uses these information to know where to send the message, but upon serializing these fields it replaces them with its own server_id and address (this could also be done in B upon receiving the message, the point being that in B these fields have been replaced with the id and address of the sender)

Or should the `send` and `recv` functions in the raft_io implementation just not care and just serialize/deserialize the content of the raft_message?

**Comment by MathieuBordere** [comment]
Thanks, it's indeed somewhat confusing.

-  `server_id` and `server_address` are used to identify the peer to send the message to. The `server_id` and `server_address` fields are however never encoded themselves and sent to the peer.
- When receiving a message, the message is [decoded](https://github.com/canonical/raft/blob/f91ac331488a5db726c50007697b431d20766373/src/uv_recv.c#L264) into a `raft_message` struct and then the `server_id` and `server_address` of the server from which the message was received is [added](https://github.com/canonical/raft/blob/f91ac331488a5db726c50007697b431d20766373/src/uv_recv.c#L272) and is obtained from [here](https://github.com/canonical/raft/blob/f91ac331488a5db726c50007697b431d20766373/src/uv_tcp_listen.c#L141) in the case of default uv tcp implementation.

**Comment by mdorier** [comment]
Tnanks!

**Comment by freeekanayaka** [comment]
@mdorier would you tell us why do you need to implement your own `raft_io`? Doing that correctly is a very difficult task. I'm wondering if your requirements could be met by modifying the regular `raft_io` implementation.

**Comment by mdorier** [comment]
My team and I have a set of software components for building distributed applications for HPC platforms. In particular we have our own network component, which uses the high-performance network interfaces provided by supercomputers, rather than TCP. We also have our own log implementation which we would like to reuse.

Writing a raft_io implementation doesn't seem that difficult. I've been on it for a couple of days and already finished the networking part (send, recv, tick, etc. along with serialization of all the appropriate data structures for network transfers). I don't expect the log part to pose much problems either. But I may be wrong, we will see down the line :-)

**Comment by MathieuBordere** [comment]
Feel free to close this issue if you have no more questions.

**Comment by freeekanayaka** [comment]
Oh see, sounds interesting :) ok, definitely an appropriate case then, there's not much that can be done upstream.

The network part (establishing connections, sending/receiving messages, encoding/decoding etc) is relatively simple. Writing to the log needs care, because of concerns like log truncation and snapshotting, plus the fact that all interfaces are asynchronous and callback-based.

**Comment by mdorier** [comment]
Thanks for your help, I'll close the issue and open new ones if I have other questions about the API :-)
