### ISSUE TITLE
[question] When is the first leader elected?

### ISSUE THREAD

**Issue by mdorier** [canonical/raft#384]
In my attempt to implement my own raft_io backend I'm facing with again something I don't quite understand: when is the first leader elected?

If I follow the example and UV-based backend, the server program starts by calling `raft_init`, then `raft_bootstrap`, which calls the `bootstrap` function from raft_io, which will (1) store the configuration as the first entry in the log, and (2) set the term  to 1 (uvSetTerm also sets voted_for to 0). Then comes a call to `raft_start`, which internally calls the `load` function of raft_io, which loads the state (in this case term = 1, voted_for = 0, start_index = 1, snaptshot set to NULL, and 1 entry loaded from the log).

Following this, in my implementation, `mraft_leader` in all servers tells me that the leader id is 0 (none of the servers have an ID of 0 as I assume this is a reserved value), and `raft_state` returns 1 (`RAFT_FOLLOWER`).

I can let it run for a few seconds (and I can confirm that the `tick` callback is being called periodically by the servers), no election gets triggered.

So, when and how is the first leader elected? Is my current understanding of the initialization sequence wrong?

**Comment by MathieuBordere** [comment]
Normally [this](https://github.com/canonical/raft/blob/f91ac331488a5db726c50007697b431d20766373/src/start.c#L224) will result in the first node becoming the leader.

**Comment by mdorier** [comment]
Ok I figured out my mistake, I wasn't setting RAFT_CHANGE as the entry type in the first entry when bootstrapping. All working fine now. Closing.
