### ISSUE TITLE
[question] Forwarding request to leader

### ISSUE THREAD

**Issue by prrlvr** [canonical/raft#391]
Hello,
As I see in [here](https://github.com/canonical/raft/blob/1357b0f45d9be1fb7c8770916283da678e9e8b43/src/client.c#L16) `raft_apply` should only be used on the leader node, otherwise the proposal is rejected.
But there are other implementation that forward theses requests to the current leader, at the price of the round-trip.
Is this behavior planned to be implemented or a PR proposing it would be accepted?

**Comment by freeekanayaka** [comment]
For clarity: the go-dqlite client has logic to automatically find the current leader (by contacting all known nodes and asking them if they are the leader), once the leader is found all requests are sent to it (and if that leader goes offline another leader search is triggered). There's no logic to automatically forward requests to the leader.

I think the automatic leader search was what @cole-miller meant.

**Comment by freeekanayaka** [comment]
> Ok I understand, thank you :) May I ask why you have made this choice to implement it in dqlite?

I assume this question was made based on the assumption that the leader-forwarding feature was implemented in dqlite (as opposed to raft). As clarified, it's not implemented anywhere, neither dqlite or raft. The go-dqlite client implements a leader-discovery feature which is a common pattern for any client of a raft-based system. As @prrlvr was mentioning, that saves an extra node round trip for every request, when compared to a leader-forwarding approach, so it was preferred.

**Comment by freeekanayaka** [comment]
A PR implementing leader-forwarding in raft as optional behavior would be welcome. However, it might be easier to implement leader-discovery in your client. YMMV.

**Comment by prrlvr** [comment]
Thank you for your deep explanations!

 I will see how I implement it and maybe submit a draft PR if I go the hard way.

**Comment by NorbertHeusser** [comment]
Hi @prrlvr 

were you able to implement some code forwarding changes to the leader ?

Might be interesting into it soner or later as well and may over to continue to work on it.
