### ISSUE TITLE
can't build on m1 mac (`<linux/xxxxx.h>` is missing)

### ISSUE THREAD

**Issue by mhw0** [canonical/raft#419]
**Steps to reproduce:**

```bash
autoreconf -i
./configure --enable-example
make
```

**Logs:**
```
src/uv_os.h:7:10: fatal error: 'linux/aio_abi.h' file not found
#include <linux/aio_abi.h>
         ^~~~~~~~~~~~~~~~~
1 error generated.
make: *** [src/libraft_la-uv.lo] Error 1
make: *** Waiting for unfinished jobs....
In file included from src/uv_append.c:5:
In file included from src/uv.h:11:
src/uv_os.h:7:10: fatal error: 'linux/aio_abi.h' file not found
#include <linux/aio_abi.h>
         ^~~~~~~~~~~~~~~~~
1 error generated.
make: *** [src/libraft_la-uv_append.lo] Error 1
In file included from src/uv_finalize.c:4:
In file included from src/uv.h:11:
src/uv_os.h:7:10: fatal error: 'linux/aio_abi.h' file not found
#include <linux/aio_abi.h>
         ^~~~~~~~~~~~~~~~~
1 error generated.
src/uv_fs.c:5:10: fatal error: 'sys/vfs.h' file not found
#include <sys/vfs.h>
         ^~~~~~~~~~~
make: *** [src/libraft_la-uv_finalize.lo] Error 1
1 error generated.
make: *** [src/libraft_la-uv_fs.lo] Error 1
In file included from src/uv_list.c:4:
In file included from src/uv.h:11:
src/uv_os.h:7:10: fatal error: 'linux/aio_abi.h' file not found
#include <linux/aio_abi.h>
         ^~~~~~~~~~~~~~~~~
1 error generated.
```

**uname -a:**
`Darwin posix.local 22.4.0 Darwin Kernel Version 22.4.0: Mon Mar  6 21:00:41 PST 2023; root:xnu-8796.101.5~3/RELEASE_ARM64_T8103 arm64`

**Comment by freeekanayaka** [comment]
Darwin/macOS is not supported at the moment, although patches would be welcome.

This specific error is due to our dependency on Linux's AIO subsystem for asynchronous disk I/O, which is not available on Darwin.

**Comment by mhw0** [comment]
There should be POSIX `aio.h`, but it's very limited. Just curious, if it already uses libuv, why would it need linux specific thing? libuv doesn't do async disk i/o? I think it does.

**Comment by freeekanayaka** [comment]
> There should be POSIX `aio.h`, but it's very limited.

Under Linux that's implemented with threads, and it's very inefficient.

>  Just curious, if it already uses libuv, why would it need linux specific thing? libuv doesn't do async disk i/o? I think it does.

It does, but using a threadpool (basically similarly to POSIX aio on Linux), so we didn't use it. The very latest version of libuv uses Linux's `io_uring` instead of a threadpool, so it should be possible to remove our dependency on Linux's AIO subsystem. However on non-Linux platforms (macOs) libuv would fallback to a threadpool, so it would be somewhat inefficient, although at least the raft library should work.
