### ISSUE TITLE
./configure fails when no external dependency is found

### ISSUE THREAD

**Issue by freeekanayaka** [canonical/raft#441]
When running `./configure` without either libuv or liblz4 installed, the script exits with this error:

```
...
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... yes
checking for pkg-config... /usr/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for UV... no
configure: error: liblz4 required but not found
Error: Process completed with exit code 1.
```

It should rather succeed (it's ok to have it fail if libuv is found but liblz4 is not found, but since libuv is not there at all in this case and `--enable-uv` was not explicitly passed, there's no reason to fail).

**Comment by MathieuBordere** [comment]
Yeah, at the time I decided that it's required unless explicitly disabled.

**Comment by freeekanayaka** [comment]
> Yeah, at the time I decided that it's required.

Just to be clear: if we want, I think it's fine to keep liblz4 required **as long as libuv is found**.

For example we could have:

```
# no libuv and no liblz4 installed
./configure # succeeds (at the moment it fails because it does not find liblz4)

# only libuv installed
./configure # fails, because we require liblz4 if libuv is used
```

In the second case, it'd be probably a tad nicer to have `./configure` succeed as well, and we already had a report from a user expecting that (https://github.com/canonical/raft/pull/377#issuecomment-1448679561 "could be improved to silently disable LZ4"), but it's okay to leave things as they are if desired.

The first case should be fixed though, and that's what this issue is about.

The idea is that when the user cares, he should use explicit flags to enable or disable stuff. If nothing explicit is passed, we take the most appropriate decisions based on what we find, but we try not to fail.

Maybe it was all obvious, but just for clarity :)

**Comment by MathieuBordere** [comment]
Because the code using lz4 is only used in the libuv related code? I think that would make sense yes.

**Comment by freeekanayaka** [comment]
> Because the code using lz4 is only used in the libuv related code?

Exactly.
