### ISSUE TITLE
AIO events get depleted during the tests

### ISSUE THREAD

**Issue by amiloradovsky** [canonical/raft#79]
An excerpt from `test-suite.log`:
```
uvFileCreate/noResources                                    [ ERROR ]
Error: test/unit/test_uv_file.c:226: assertion failed: rv_ == UV__ERROR (0 == 1)
Error: child killed by signal 6 (Aborted)
```
Digging this up we're coming to:
```
$ cat /proc/sys/fs/aio-nr
768
```
IDK what to do next. How to "drop" the events, for example.

**Comment by freeekanayaka** [comment]
Yeah this unit test is not particularly robust, it basically assumes that no other process is consuming AIO events. This should be generally true for an isolated host environment which is devoted to just running the test suite (e.g. it works perfectly on Travis). However, I guess you have some other unrelated system service or application running that makes use of AIO? Maybe raft itself via LXD?

I'll change the code so this test is skipped if ```/proc/sys/fs/aio-nr``` contains any number greater than ```0```, still not perfect but probably good enough.
