### ISSUE TITLE
How to compile/use the test case in "test\fuzzy"?

### ISSUE THREAD

**Issue by 179416326** [canonical/raft#93]
Hi, freeekanayaka, I have run /example/cluster very well, but how do i use the test case in "test\fuzzy"? What is the procedure? Would u please give a example? Thanks.

**Comment by freeekanayaka** [comment]
To run the tests, invoke ```make check```. The best thing is to look at the ```.travis.yml``` file in the repository, which contains the build and test instruction for the [Travis builds](https://travis-ci.org/canonical/raft/) of raft.

**Comment by 179416326** [comment]
Thanks, following the Travic builds, i can run test now, but still there were some errors, here is my test-suite.log, i cannot find anything wrong. Maybe my clang version?  Please have a look.

clang version 3.8.0-2ubuntu4 (tags/RELEASE_380/final)
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin

**Comment by 179416326** [comment]
[Uploading test-suite.log…]()

**Comment by 179416326** [comment]
[test-suite.log](https://github.com/canonical/raft/files/3935821/test-suite.log)

**Comment by freeekanayaka** [comment]
It seems you are running the tests as root, or as some sort of privileged user. At least 2 of the 3 tests that are failing should be due to that.

**Comment by 179416326** [comment]
Yes, that is the problem, all 5 tests passed.  Besides raft example, is there any dqlite test example to follow?

**Comment by freeekanayaka** [comment]
> Yes, that is the problem, all 5 tests passed. Besides raft example, is there any dqlite test example to follow?

I don't understand this question. What are you trying to do?

**Comment by 179416326** [comment]
I mean is there any example to test dqlite function in RAFT, like "./example/cluster" in RAFT.

**Comment by freeekanayaka** [comment]
Look at the [dqlite demo program](https://github.com/canonical/go-dqlite#demo). Note that it's written in Go, not in C, because at the moment there is no official C **client** for dqlite, only the **server** is in C.

**Comment by 179416326** [comment]
Thanks, i will test the demo.
