### ISSUE TITLE
How to cross-compile raft/dqlite in other platform?

### ISSUE THREAD

**Issue by 179416326** [canonical/raft#94]
Hi freeekanayaka, i have tested raft/dqlite well in Ubuntu(v16.04, INTEL-X64), now i want to test them in other platform, like ARM, what do i need to change to specify the cross-compiler?

**Comment by freeekanayaka** [comment]
I don't think there's anything specific to change. For simplicity I'd recommend to compile directly on the target platform, instead of cross-compiling. Please free free to re-open this issue if you find out that something needs to be change to allow for cross-compilation.
